/*
 * This file is generated by jOOQ.
*/
package com.jooq.madhan.sample.domain.tables;


import com.jooq.madhan.sample.domain.Jooqschema;
import com.jooq.madhan.sample.domain.Keys;
import com.jooq.madhan.sample.domain.tables.records.RevenueDetailJobParametersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevenueDetailJobParameters extends TableImpl<RevenueDetailJobParametersRecord> {

    private static final long serialVersionUID = -199415450;

    /**
     * The reference instance of <code>jooqschema.revenue_detail_job_parameters</code>
     */
    public static final RevenueDetailJobParameters REVENUE_DETAIL_JOB_PARAMETERS = new RevenueDetailJobParameters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RevenueDetailJobParametersRecord> getRecordType() {
        return RevenueDetailJobParametersRecord.class;
    }

    /**
     * The column <code>jooqschema.revenue_detail_job_parameters.id</code>.
     */
    public final TableField<RevenueDetailJobParametersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jooqschema.revenue_detail_job_parameters.number_of_records</code>.
     */
    public final TableField<RevenueDetailJobParametersRecord, Integer> NUMBER_OF_RECORDS = createField("number_of_records", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>jooqschema.revenue_detail_job_parameters.run_status</code>.
     */
    public final TableField<RevenueDetailJobParametersRecord, Byte> RUN_STATUS = createField("run_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>jooqschema.revenue_detail_job_parameters</code> table reference
     */
    public RevenueDetailJobParameters() {
        this("revenue_detail_job_parameters", null);
    }

    /**
     * Create an aliased <code>jooqschema.revenue_detail_job_parameters</code> table reference
     */
    public RevenueDetailJobParameters(String alias) {
        this(alias, REVENUE_DETAIL_JOB_PARAMETERS);
    }

    private RevenueDetailJobParameters(String alias, Table<RevenueDetailJobParametersRecord> aliased) {
        this(alias, aliased, null);
    }

    private RevenueDetailJobParameters(String alias, Table<RevenueDetailJobParametersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jooqschema.JOOQSCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RevenueDetailJobParametersRecord> getPrimaryKey() {
        return Keys.KEY_REVENUE_DETAIL_JOB_PARAMETERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RevenueDetailJobParametersRecord>> getKeys() {
        return Arrays.<UniqueKey<RevenueDetailJobParametersRecord>>asList(Keys.KEY_REVENUE_DETAIL_JOB_PARAMETERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevenueDetailJobParameters as(String alias) {
        return new RevenueDetailJobParameters(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RevenueDetailJobParameters rename(String name) {
        return new RevenueDetailJobParameters(name, null);
    }
}
