/*
 * This file is generated by jOOQ.
*/
package com.jooq.madhan.sample.domain;


import com.jooq.madhan.sample.domain.tables.Author;
import com.jooq.madhan.sample.domain.tables.AuthorBook;
import com.jooq.madhan.sample.domain.tables.Book;
import com.jooq.madhan.sample.domain.tables.records.AuthorBookRecord;
import com.jooq.madhan.sample.domain.tables.records.AuthorRecord;
import com.jooq.madhan.sample.domain.tables.records.BookRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>jooqschema</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = UniqueKeys0.KEY_AUTHOR_PRIMARY;
    public static final UniqueKey<AuthorBookRecord> KEY_AUTHOR_BOOK_PRIMARY = UniqueKeys0.KEY_AUTHOR_BOOK_PRIMARY;
    public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = UniqueKeys0.KEY_BOOK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorBookRecord, AuthorRecord> FK_AB_AUTHOR = ForeignKeys0.FK_AB_AUTHOR;
    public static final ForeignKey<AuthorBookRecord, BookRecord> FK_AB_BOOK = ForeignKeys0.FK_AB_BOOK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = createUniqueKey(Author.AUTHOR, "KEY_author_PRIMARY", Author.AUTHOR.ID);
        public static final UniqueKey<AuthorBookRecord> KEY_AUTHOR_BOOK_PRIMARY = createUniqueKey(AuthorBook.AUTHOR_BOOK, "KEY_author_book_PRIMARY", AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID);
        public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = createUniqueKey(Book.BOOK, "KEY_book_PRIMARY", Book.BOOK.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AuthorBookRecord, AuthorRecord> FK_AB_AUTHOR = createForeignKey(com.jooq.madhan.sample.domain.Keys.KEY_AUTHOR_PRIMARY, AuthorBook.AUTHOR_BOOK, "fk_ab_author", AuthorBook.AUTHOR_BOOK.AUTHOR_ID);
        public static final ForeignKey<AuthorBookRecord, BookRecord> FK_AB_BOOK = createForeignKey(com.jooq.madhan.sample.domain.Keys.KEY_BOOK_PRIMARY, AuthorBook.AUTHOR_BOOK, "fk_ab_book", AuthorBook.AUTHOR_BOOK.BOOK_ID);
    }
}
