/*
 * This file is generated by jOOQ.
*/
package com.jooq.madhan.sample.domain.tables.records;


import com.jooq.madhan.sample.domain.tables.RevenueDetailJobParameters;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevenueDetailJobParametersRecord extends UpdatableRecordImpl<RevenueDetailJobParametersRecord> implements Record3<Integer, Integer, Byte> {

    private static final long serialVersionUID = -567338260;

    /**
     * Setter for <code>jooqschema.revenue_detail_job_parameters.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooqschema.revenue_detail_job_parameters.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooqschema.revenue_detail_job_parameters.number_of_records</code>.
     */
    public void setNumberOfRecords(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooqschema.revenue_detail_job_parameters.number_of_records</code>.
     */
    public Integer getNumberOfRecords() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jooqschema.revenue_detail_job_parameters.run_status</code>.
     */
    public void setRunStatus(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooqschema.revenue_detail_job_parameters.run_status</code>.
     */
    public Byte getRunStatus() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RevenueDetailJobParameters.REVENUE_DETAIL_JOB_PARAMETERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RevenueDetailJobParameters.REVENUE_DETAIL_JOB_PARAMETERS.NUMBER_OF_RECORDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return RevenueDetailJobParameters.REVENUE_DETAIL_JOB_PARAMETERS.RUN_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNumberOfRecords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getRunStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevenueDetailJobParametersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevenueDetailJobParametersRecord value2(Integer value) {
        setNumberOfRecords(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevenueDetailJobParametersRecord value3(Byte value) {
        setRunStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RevenueDetailJobParametersRecord values(Integer value1, Integer value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevenueDetailJobParametersRecord
     */
    public RevenueDetailJobParametersRecord() {
        super(RevenueDetailJobParameters.REVENUE_DETAIL_JOB_PARAMETERS);
    }

    /**
     * Create a detached, initialised RevenueDetailJobParametersRecord
     */
    public RevenueDetailJobParametersRecord(Integer id, Integer numberOfRecords, Byte runStatus) {
        super(RevenueDetailJobParameters.REVENUE_DETAIL_JOB_PARAMETERS);

        set(0, id);
        set(1, numberOfRecords);
        set(2, runStatus);
    }
}
